CREATE DATABASE employee

-- EMPLOYEE TABLE
CREATE TABLE EMPLOYEE
(
emp_id NVARCHAR(800),
emp_name varchar(8000),
salary bigint,
dept_id NVARCHAR(800),
manager_id NVARCHAR(800)
)
-- DELETE THE TABLE EMPLOYEE
DROP TABLE EMPLOYEE;



SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES ( 'E1' ,'CHIRAG SAHU',12000,'D1','M1')


INSERT INTO EMPLOYEE
VALUES ( 'E2' ,'MUKESH YADAV',12000,'D1','M1')


INSERT INTO EMPLOYEE
VALUES ( 'E3' ,'YASH MSIHRA',12000,'D2','M2')

INSERT INTO EMPLOYEE
VALUES ( 'E4' ,'PARAG GUNJAL',12000,'D2','M2')


INSERT INTO EMPLOYEE
VALUES ( 'E5' ,'SUMIT SHUKLA',12000,'D10','M3')


INSERT INTO EMPLOYEE
VALUES ( 'E6' ,'NEW INTERN',12000,'D10','M3')
-- DEPARTMENT TABLE:
CREATE TABLE DEPARTMENT
(
dept_id NVARCHAR(800),
dept_name varchar(8000),
)

SELECT * FROM DEPARTMENT


-- DELETE THE TABLE EMPLOYEE
DROP TABLE DEPARTMENT;

INSERT INTO DEPARTMENT
VALUES ( 'D1' ,'IT')
INSERT INTO DEPARTMENT
VALUES ( 'D2' ,'OPERATION')
INSERT INTO DEPARTMENT
VALUES ( 'D3' ,'DEVELOPER')
INSERT INTO DEPARTMENT
VALUES ( 'D4' ,'SDE')


-- SELECT QUERY OF EMPLOYEE AND DEPARTMENT:
SELECT * FROM EMPLOYEE

SELECT * FROM DEPARTMENT


-- FETCH THE EMPLOYEE NAME AND THE DEPARTMENT NAME THEY BELONG TO ....

-- INNER JOIN / JOIN
SELECT e.emp_name, d.dept_name
FROM EMPLOYEE e     
INNER JOIN DEPARTMENT d on e.dept_id = d.dept_id



-- FETCH ALL THE EMPLOYEE NAME AND THEIR DEPARTMENT NAME THEY BELONG TO ....

-- LEFT JOIN
SELECT e.emp_name, d.dept_name
FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d on e.dept_id = d.dept_id

-- FORMULA OF LEFT JOIN : INNER JOIN + ANY ADDITIONAL RECORDS IN THE LEFT TABLE.


-- FETCH ALL THE EMPLOYEE NAME AND THEIR DEPARTMENT NAME THEY BELONG TO ....

-- RIGHT JOIN
SELECT e.emp_name, d.dept_name
FROM EMPLOYEE e
RIGHT JOIN DEPARTMENT d on e.dept_id = d.dept_id

-- FORMULA OF RIGHT JOIN : INNER JOIN + ANY ADDITIONAL RECORDS IN THE RIGHT TABLE.
